### ISSUE TITLE
k-ext 后续开发任务

### ISSUE THREAD

**Issue by pz9115** [plctlab/riscv-gnu-toolchain#12]
1. 构筑完整的CI对repo进行测试 @lazyparser
https://github.com/WuSiYu/riscv-gcc
https://github.com/pz9115/riscv-binutils-gdb/tree/riscv-binutils-2.35-k

2. 由 @WuSiYu 在 @mollybuild的帮助下进行测试用例开发
 
3. 在b-ext额外分支添加完成后进行整合

**Comment by lazyparser** [comment]
nice try, but

需要补充的开发计划：

如何定义【完成】？

-  有代码没测试用例算么？
-  需要有文档么？什么样的格式？
-  写好的代码提交（PR）到哪个仓库的哪个分支？
-  最终如何提交到upstream？

**Comment by pz9115** [comment]
1. 最终提交到upstream后算做任务“完成”
2. 依据以往提交的历史，可以先提交代码，后补充测试用例和修正补丁
3. 建议在个人仓库的wiki中附上对应扩展工具链的使用说明，如参数选择，交叉编译库等
4. 写好的代码先上传到个人仓库，经过CI验证后，修复所有回归测试反馈的bug，通过回归测试后，提交PR至riscv/riscv-gcc riscv/riscv-gdb-binutils 仓库下的对应分支(上述是基于对应分支fork后的合并，如果没有对应分支，则新创建一个)
5. 待mentor对提交的代码review之后，对反馈进行修复，最后PR至upstream

**Comment by lazyparser** [comment]
better

**Comment by lazyparser** [comment]
构建CI测试的必要步骤，和回归测试的用例说明，每一个扩展任务都说明一下。

已经有一个初步的CI：

https://github.com/plctlab/riscv-gnu-toolchain/blob/krypto-scalar-dev/jenkinsfile.ubuntu1804

可以直接发起PR修改这个CI

**Comment by lazyparser** [comment]
@pz9115 更新下进展

**Comment by pz9115** [comment]
目前K扩展已填加完成，GCC与Binutils部分配有对应的测试case，已构建CI验证并且通过，PR等待mentor review中。

**Comment by pz9115** [comment]
目前K扩展已填加完成，GCC与Binutils部分配有对应的测试case，已构建CI验证并且通过，PR等待mentor review中。

**Comment by pz9115** [comment]
Binutils工作进展:K扩展已更新至public review版本，并与B扩展public review版本进行了合并，PR已根据mantainer的意见修改并approval https://github.com/riscv/riscv-binutils-gdb/pull/254
