### ISSUE TITLE
b-ext 开发计划

### ISSUE THREAD

**Issue by pz9115** [plctlab/riscv-gnu-toolchain#14]
1. 由 @pz9115 在Andes repo(https://github.com/riscv/riscv-binutils-gdb/tree/riscv-binutils-experiment) 的基础上继续进行指令添加工作

2. 构筑完整的CI对repo进行测试 @lazyparser
https://github.com/pz9115/riscv-gcc/tree/b-ext-dev
https://github.com/pz9115/riscv-binutils-gdb/tree/bitmanip-dev

3. 在添加工作完成后，由 @mollybuild协助@pz9115进行测试用例的开发

**Comment by lazyparser** [comment]
nice try:

需要补充的开发计划：

如何定义【完成】？
- 有代码没测试用例算么？
- 需要有文档么？什么样的格式？
- 写好的代码提交（PR）到哪个仓库的哪个分支？
- 最终如何提交到upstream？

**Comment by pz9115** [comment]
B扩展 v1.0.0-rc gcc部分已merge进https://github.com/riscv/riscv-gcc/pull/253
binutils非public review部分(zbe_zbf_zbm_zbp_zbr_zbt)根据mantainer意见进行了修改并approval，后续转入dev 分支保留https://github.com/riscv/riscv-binutils-gdb/pull/255 , public review部分合入K扩展，https://github.com/riscv/riscv-binutils-gdb/pull/254, 等待merge到experimental分支中
